nelmio_api_doc:
    documentation:
        info:
            title: Filmstriben
            description: Filmstriben REST service.
            version: 2.x-dev
    areas: # to filter documented areas
        path_patterns:
            - ^/content|files|list|menu|taxonomy|configuration
