services:
    fixture_loader:
        class: App\Services\FixtureLoader
    image_converter:
        class: App\Services\ImageConverter
    query_lexer:
        class: App\Services\SearchQueryLexer
    query_parser:
        class: App\Services\SearchQueryParser
        arguments: ['@query_lexer']
